version: "3.3"

services:
  proxy:
    container_name: rs-proxy
    build: proxy/.
    ports:
      - 80:80
    restart: on-failure:10

  database:
    container_name: rs-database
    image: amazon/dynamodb-local
    command: -jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data/
    ports:
      - 8000:8000

  api:
    container_name: rs-api
    build: api/.
    env_file:
      - .env
    depends_on:
      - database
    volumes:
      - ./api:/app
      - ./data:/data
    stdin_open: true
    tty: true

  api-test:
    container_name: rs-test
    build: api/.
    env_file:
      - .env
    command: "ptw"
    volumes:
      - ./api:/app

  worker:
    container_name: rs-worker
    build:
      context: .
      dockerfile: ./worker/Dockerfile
    restart: on-failure
    env_file:
      - .env

  redis:
    container_name: rs-redis
    build: redis/.
    command: redis-server --appendonly yes
