version: "3.3"

services:
  proxy:
    container_name: rs-proxy-p
    build:
      context: proxy/.
      dockerfile: Dockerfile
    ports:
      - 80:80
    restart: on-failure

  api:
    container_name: rs-api-p
    build:
      context: api/.
      dockerfile: Dockerfile-prod
    env_file:
      - .prod-env
    restart: on-failure
    volumes:
      - ./data:/data
      - ./api/migrations:/app/migrations

  worker:
    container_name: rs-worker-p
    build:
      context: .
      dockerfile: ./worker/Dockerfile
    env_file:
      - .prod-env
    volumes:
      - ./data:/data
    restart: on-failure

  redis:
    container_name: rs-redis-p
    image: redis:6-buster

