version: "3.3"

services:
  proxy:
    container_name: rs-proxy
    build:
      context: proxy/.
      dockerfile: Dockerfile
    ports:
      - 80:80
    restart: on-failure

  api:
    container_name: rs-api
    build:
      context: api/.
      dockerfile: Dockerfile-prod
    env_file:
      - .env
    depends_on:
      - database
    restart: on-failure
    volumes:
      - ./data:/data
      - ./api/migrations:/app/migrations

  worker:
    container_name: rs-worker
    build:
      context: .
      dockerfile: ./worker/Dockerfile
    env_file:
      - .env
    volumes:
      - ./data:/data
    restart: on-failure

  redis:
    container_name: rs-redis
    build: redis/.
    command: redis-server --appendonly yes
    env_file:
      - .env

