FROM ubuntu:19.10

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update -y
RUN apt-get upgrade -y
RUN apt-get update -y && apt-get install curl -y
RUN apt-get install libpq-dev gcc python3-dev musl-dev python3-pip -y
RUN pip3 install gunicorn
WORKDIR /app

COPY requirements/base.txt /app/requirements/base.txt
RUN pip3 install -r /app/requirements/base.txt

COPY . /app

RUN chmod +X start_prod.sh

ENV FLASK_APP main_app.py
ENV FLASK_ENV production
ENV PYTHONUNBUFFERED 1

# Fixing utc, timezone
ENV LC_ALL C.UTF-8
ENV LANG C.UTF-8
ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update && apt-get install -y --no-install-recommends tzdata  && rm -rf /var/lib/apt/lists/*
RUN ln -fs /usr/share/zoneinfo/Asia/Shanghai /etc/localtime  && dpkg-reconfigure --frontend noninteractive tzdata

CMD ["/bin/sh","./start_prod.sh"]